# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_auto_20171022_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
