# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import memo.models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_auto_20171025_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memo',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='memo',
            name='image',
            field=models.ImageField(blank=True, upload_to=memo.models.memo_directory_path),
        ),
    ]
