# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0005_remove_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
