# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20171017_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='token',
        ),
    ]
