# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20171025_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='access_key',
            field=models.CharField(blank=True, max_length=260),
        ),
    ]
