# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20171025_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
